#
# Deployment of the SUSI Server
#
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: susi-server
  namespace: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: susi-server
    spec:
      volumes:
      - name: data-store
        emptyDir: {}
      containers:
      - image: chiragw15/susi_server:latest
        name: susi-server
        volumeMounts:
          - mountPath: /data/
            name: accounts-data-disk
        livenessProbe:
          httpGet:
            path: /susi/status.json
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 3
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: accounts-data-disk
        gcePersistentDisk:
          pdName: accounts-data-disk
          fsType: ext4
      restartPolicy: Always