#
# Deployment of the SUSI Server
#
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: susi-server
  namespace: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: susi-server
    spec:
      volumes:
      - name: data-store
        emptyDir: {}
      containers:
      - image: chiragw15/susi_server:latest
        name: susi-server
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: accounts-data-disk
        gcePersistentDisk:
          pdName: accounts-data-disk
          fsType: ext4
      restartPolicy: Always